name: firebase_tool
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  firedart: ^0.9.8
  uuid: ^4.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
